services:
  backend:
    build:
      context: backendfastapi
      dockerfile: Dockerfile
    ports:
      - 8090:8000
    # depends_on:
    #   - db_service
    env_file:
      - .env
    #volumes:
     # - ./backendfastapi/src:/app
    develop:
      watch:
      - action: rebuild
        path: backendfastapi/requirements.txt
      - action: rebuild
        path: backendfastapi/backend.Dockerfile
      - action: sync
        path: backendfastapi/src
        target: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#   db_service:
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     env_file:
#       - .db_env
#     volumes:
#       - managed_db_data:/var/lib/postgresql/data

# volumes:
#   managed_db_data: